old_sound_rabbit_mq:
    connections:
        default:
            host: 'localhost'
            port: '5672'
            user: 'guest'
            password: 'guest'
            vhost: '/'
            lazy: true
    producers:
        # EXAMPLE 1
        example1:
            connection: default
            exchange_options: {name: 'example1', type: fanout, passive: false, durable: true, auto_delete: false}
        # EXAMPLE 2
        example2:
            connection: default
            exchange_options: {name: 'example2', type: fanout, passive: false, durable: true, auto_delete: false}
    consumers:
        # EXAMPLE 1
        example1:
            connection: default
            exchange_options: {name: 'example1', type: fanout, passive: false, durable: true, auto_delete: false}
            queue_options:
                name: 'ha_example1'
                arguments: { x-dead-letter-exchange: ['S', 'dead_letter'], 'x-message-ttl': ['I', 200]  }
            callback:  example1_service
            idle_timeout:     300
        example1_dead_letter:
            connection: default
            exchange_options: {name: 'dead_letter', type: fanout, passive: false, durable: true, auto_delete: false}
            queue_options:    {name: 'ha_dead_letter'}
            callback:         example1_dead_letter_service
            idle_timeout:    300
        # EXAMPLE 2
        example2:
            connection: default
            exchange_options: {name: 'example2', type: fanout, passive: false, durable: true, auto_delete: false}
            queue_options:
                name: 'ha_example2'
                arguments: { x-dead-letter-exchange: ['S', 'dead_letter_requeue'] }
            callback:  example2_service
            idle_timeout:     300
        example2_dead_letter_requeue:
            connection: default
            exchange_options: {name: 'dead_letter_requeue', type: fanout, passive: false, durable: true, auto_delete: false}
            queue_options:    {name: 'ha_dead_letter_requeue'}
            callback:         example2_dead_letter_requeue_service
            idle_timeout:    300

